apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio-python
  template:
    metadata:
      labels:
        app: microservicio-python
    spec:
      containers:
      - name: microservicio-python
        image: microservicio-python:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongo:27017/users"
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-python
spec:
  selector:
    app: microservicio-python
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
