apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-python
  template:
    metadata:
      labels:
        app: microservicio-python
    spec:
      containers:
      - name: microservicio-python
        image: mopito/tfm:python
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-python
spec:
  selector:
    app: microservicio-python
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
